version: '3.3'
services:

    smanga:
        container_name: smanga
        ports:
            - '8097:80'
        volumes:
            - './compress:/compress'
            - './poster:/poster'
            - './config:/config'
            - '/mnt:/mnt'
        networks:
            - default
        image: lkw199711/smanga:mysql

networks:
  default:
    name: smanga