name: Build Smanga Docker

on:
    workflow_dispatch:

jobs:
  build:
    name: Build Smanga Docker
    runs-on: ubuntu-latest
    steps:
      - 
        name: Checkout
        uses: actions/checkout@master
      
      - name: Set Version
        id: set-version
        run: |
          SMANGA_VERSION=$(cat package.json | grep 'version' | cut -d\" -f4 | head -1)
          echo "::set-output name=version::${SMANGA_VERSION}"

      -
        name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      -
        name: Build Web
        run: npm install && npm run build

      - 
        name: Set Up QEMU
        uses: docker/setup-qemu-action@v2

      - 
        name: Set Up Buildx
        uses: docker/setup-buildx-action@v2
        
      - 
        name: Login DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - 
        name: Build
        uses: docker/build-push-action@v3
        with:
          context: .
          file: docker/Dockerfile
          platforms: |
            linux/amd64
            linux/arm64/v8
          push: true
          build-args: |
            SMANGA_VERSION=${{ steps.set-version.outputs.version }}
            SMANGA_BASE_NAME=${{ secrets.DOCKER_USERNAME }}
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/smanga:${{ steps.set-version.outputs.version }}
            ${{ secrets.DOCKER_USERNAME }}/smanga:latest


  build_mysql:
    needs: [build]
    name: Build Smanga Mysql Docker
    runs-on: ubuntu-latest
    steps:
      - 
        name: Checkout
        uses: actions/checkout@master
      
      - name: Set Version
        id: set-version
        run: |
          SMANGA_VERSION=$(cat package.json | grep 'version' | cut -d\" -f4 | head -1)
          echo "::set-output name=version::${SMANGA_VERSION}"

      - 
        name: Set Up QEMU
        uses: docker/setup-qemu-action@v2

      - 
        name: Set Up Buildx
        uses: docker/setup-buildx-action@v2
        
      - 
        name: Login DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - 
        name: Build
        uses: docker/build-push-action@v3
        with:
          context: .
          file: docker/mysql.Dockerfile
          platforms: |
            linux/amd64
            linux/arm64/v8
          push: true
          build-args: |
            SMANGA_VERSION=${{ steps.set-version.outputs.version }}
            SMANGA_BASE_NAME=${{ secrets.DOCKER_USERNAME }}
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/smanga:${{ steps.set-version.outputs.version }}-mysql
            ${{ secrets.DOCKER_USERNAME }}/smanga:mysql

  update:
    needs: [build, build_mysql]
    name: Update Dockerhub Docs
    runs-on: ubuntu-latest
    steps:
      - 
        name: Checkout
        uses: actions/checkout@master
        
      - 
        name: Login DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      -
        name: Docker Hub Description
        uses: peter-evans/dockerhub-description@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: ${{ secrets.DOCKER_USERNAME }}/smanga
          short-description: A simple cartoon browser
          readme-filepath: ./README.md