name: Build Smanga Debian Docker

on:
    workflow_dispatch:
    push:
      branches:
        - master
      paths:
        - package.json

jobs:
  build:
    name: Build Smanga Docker
    runs-on: ubuntu-latest
    steps:
      - 
        name: Checkout
        uses: actions/checkout@master
      
      - 
        name: Set Version
        id: set-version
        run: |
          SMANGA_VERSION=$(cat package.json | grep 'version' | cut -d\" -f4 | head -1)
          echo "version=${SMANGA_VERSION}" >> $GITHUB_OUTPUT

      -
        name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: '14'

      -
        run: npm install -g @vue/cli

      -
        name: Build Web
        run: npm install && npm run build

      - 
        name: Set Up QEMU
        uses: docker/setup-qemu-action@v2

      - 
        name: Set Up Buildx
        uses: docker/setup-buildx-action@v2
        
      - 
        name: Login DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - 
        name: Build
        uses: docker/build-push-action@v4
        with:
          context: .
          file: docker/debian/Dockerfile
          platforms: |
            linux/amd64
            linux/arm64/v8
          push: true
          build-args: |
            SMANGA_VERSION=${{ steps.set-version.outputs.version }}
            SMANGA_BASE_NAME=${{ secrets.DOCKER_USERNAME }}
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/smanga:debian-${{ steps.set-version.outputs.version }}
            ${{ secrets.DOCKER_USERNAME }}/smanga:debian
