name: Build Smanga Base Docker

on:
    workflow_dispatch:
    push:
      branches:
        - master
      paths:
        - docker/base.Dockerfile
        - .github/workflows/docker_base.yml

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - 
        name: Checkout
        uses: actions/checkout@master
      
      - 
        name: Set Version
        id: set-version
        run: |
          SMANGA_VERSION=$(jq -r '.version' package.json)
          echo "version=${SMANGA_VERSION}" >> $GITHUB_OUTPUT

      - 
        name: Set Up QEMU
        uses: docker/setup-qemu-action@v3

      - 
        name: Set Up Buildx
        uses: docker/setup-buildx-action@v2
        
      - 
        name: Login DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - 
        name: Build Base
        uses: docker/build-push-action@v4
        with:
          context: .
          file: docker/base.Dockerfile
          platforms: |
            linux/amd64
            linux/arm64/v8
          push: true
          build-args: |
            SMANGA_VERSION=${{ steps.set-version.outputs.version }}
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/smanga-base:${{ steps.set-version.outputs.version }}
            ${{ secrets.DOCKER_USERNAME }}/smanga-base:latest
